# Generated by Django 2.2.16 on 2020-11-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(verbose_name='date pubbed')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textField', models.CharField(max_length=200)),
                ('testBool', models.BooleanField(default=1, verbose_name='test bool')),
                ('forms', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Form')),
            ],
        ),
    ]
