# Generated by Django 3.1.2 on 2020-11-20 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('pubdate', models.DateTimeField(verbose_name='date pubbed')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('formType', models.CharField(choices=[('TF', 'Text Field'), ('CL', 'Checklist'), ('NM', 'Number'), ('DD', 'Dropdown Menu')], default='', max_length=20)),
                ('options', models.CharField(blank=True, max_length=200)),
                ('requiredBool', models.BooleanField(default=1, verbose_name='field required')),
                ('visibleBool', models.BooleanField(default=1, verbose_name='field visible')),
                ('order', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='field order')),
                ('forms', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field', to='core.form')),
            ],
        ),
    ]
