# Generated by Django 2.2.16 on 2020-11-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='testBool',
        ),
    ]
