# Generated by Django 2.2.16 on 2020-12-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_display',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.FormDisplay'),
        ),
    ]
