# Generated by Django 2.2.16 on 2020-11-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_field_testbool'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='testBool',
            field=models.BooleanField(default=1, verbose_name='test bool'),
        ),
    ]
