# Generated by Django 3.1.3 on 2021-02-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210206_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='walker',
        ),
    ]
