# Generated by Django 2.2.16 on 2020-12-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201203_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='form_display',
        ),
        migrations.DeleteModel(
            name='FormDisplay',
        ),
    ]
