# Generated by Django 3.1.3 on 2021-02-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_match_walker'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='walker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walker', to='core.walker'),
        ),
    ]
