# Generated by Django 2.2.16 on 2020-11-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_field_testbool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='textField',
            new_name='label',
        ),
    ]
