# Generated by Django 2.2.16 on 2020-11-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201114_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='formType',
            field=models.CharField(choices=[('TF', 'Text Field'), ('CL', 'Checklist'), ('NM', 'Number'), ('DD', 'Dropdown Menu')], default='', max_length=20),
        ),
    ]
