# Generated by Django 2.2.16 on 2020-11-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201115_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='field order'),
        ),
    ]
