# Generated by Django 2.2.16 on 2020-11-15 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_field_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='field order'),
        ),
    ]
