import os

env = os.environ


# All values set in heroku configs
# AWS_STORAGE_BUCKET_NAME = 'animal-aid-local'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_FILE_OVERWRITE = True
# AWS_ACCESS_KEY_ID = "***REMOVED***"
# AWS_SECRET_ACCESS_KEY = "***REMOVED***"
# AWS_S3_REGION_NAME = "us-east-2"
# AWS_S3_ENDPOINT_URL = 'https://s3.us-east-2.amazonaws.com'

AWS_STORAGE_BUCKET_NAME = env['AWS_STORAGE_BUCKET_NAME']
AWS_S3_CUSTOM_DOMAIN = env['AWS_S3_CUSTOM_DOMAIN']
AWS_S3_FILE_OVERWRITE = env['AWS_S3_FILE_OVERWRITE']
AWS_ACCESS_KEY_ID = env['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = env['AWS_SECRET_ACCESS_KEY']
AWS_S3_REGION_NAME = env['AWS_S3_REGION_NAME']
AWS_S3_ENDPOINT_URL = env['AWS_S3_ENDPOINT_URL']

AWS_S3_SIGNATURE_VERSION = 's3v4'
S3DIRECT_DIR = 's3direct'